#!/usr/bin/env bash

IFS='/' read -ra ADDR <<<"$1"
module="${ADDR[0]}"
old_name="${ADDR[1]}"
new_name="$2"
ag -l "$old_name" | xargs sed -i "s/$old_name/$new_name/g" &&
  mv "./lib/$module/$old_name" "./lib/$module/$new_name" &&
  git add . &&
  git commit -m "Replaced $old_name with $new_name"
