name: Publish New Sensor Scatterplot Package Version
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish -w @sjvair/sensor-scatterplot --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
